const subjects = [
  { moduleCode: "GINF31", subject: "Programmation orientée objet : JAVA" },
  { moduleCode: "GINF32", subject: "Assurance contrôle de qualité (ISO 9001)" },
  { moduleCode: "GINF33", subject: "Modélisation orientée objet UML" },
  {
    moduleCode: "GINF34",
    subject: "Optimisation et Qualité de base de données",
  },
  { moduleCode: "GINF35", subject: "Administration systèmes" },
  { moduleCode: "GINF36", subject: "Espagnol 2 et Allemand" },
  { moduleCode: "GINF41", subject: "Introduction à J2EE" },
  { moduleCode: "GINF42", subject: "Gestion des données complexes" },
  { moduleCode: "GINF43", subject: "Traitement d'image" },
  { moduleCode: "GINF44", subject: "Programmation Déclarative" },
  { moduleCode: "GINF45", subject: "Sécurité des systèmes" },
  { moduleCode: "GINF46", subject: "Économie et Comptabilité 2" },
  { moduleCode: "GINF31", subject: "XML et Applications" },
  { moduleCode: "GINF32", subject: "Cycle de Vie Logiciel et Méthodes agiles" },
  { moduleCode: "GINF33", subject: "Interaction Homme Machine" },
  {
    moduleCode: "GINF34",
    subject: "Administration et Sécurité des bases de données",
  },
  { moduleCode: "GINF35", subject: "Programmation systèmes" },
  { moduleCode: "GINF36", subject: "Anglais professionnel" },
  { moduleCode: "GINF41", subject: "Programmation en c#" },
  { moduleCode: "GINF42", subject: "Gestion des données distribuées" },
  { moduleCode: "GINF43", subject: "Vision numérique" },
  { moduleCode: "GINF44", subject: "Technique Algorithmique Avancée" },
  { moduleCode: "GINF45", subject: "Cryptographie" },
  { moduleCode: "GINF46", subject: "Projets Collectifs et Stages" },
  { moduleCode: "GINF32", subject: "Maîtrise et optimisation des processus" },
  { moduleCode: "GINF34", subject: "Base de données NoSQL" },
  { moduleCode: "GINF36", subject: "Techniques de communication" },
  { moduleCode: "GINF42", subject: "Cloud Computing et infogérance" },
  { moduleCode: "GINF43", subject: "Processus Stochastique" },
  { moduleCode: "GINF46", subject: "Management de Projet" },
];

module.exports = subjects;
