FROM node:21.5.0-alpine

WORKDIR /usr/src/app

# Install OS build dependencies
RUN apk add --no-cache make gcc g++ python3 && \
    npm cache clean --force && \
    npm install && \
    npm rebuild bcrypt --build-from-source && \
    apk del make gcc g++ python3

# Copy package files
COPY package*.json ./

# Install npm dependencies
RUN npm install --silent

# Copy the rest of the application code
COPY . .

# Expose the necessary port
EXPOSE 3000

# Set environment variables if needed
# ENV NODE_ENV production

# Start the application
CMD ["npm", "run", "dev"]


